---

- hosts: postgresql
  remote_user: vagrant
  become: yes
  roles:
    - postgresql

- hosts: airflow_webserver
  remote_user: vagrant
  become: yes
  vars:
    - postgres_init_db: true
    - airflow_services:
        - airflow-webserver
        - airflow-scheduler
  roles:
    - airflow
