---

- name: Create Airflow group
  group:
    name: "{{ airflow_group }}"
    state: present

- name: Create Airflow user
  user:
    name: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    shell: /bin/bash
    state: present

- name: Create Airflow home folder
  file:
    path: "{{ airflow_home }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Install prerequisites packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ airflow_required_libs }}"

- name: Install Celery
  pip:
    name: celery
    version: "{{ celery_version }}"
  when: airflow_executor == "CeleryExecutor"

- name: Install extra Celery packages
  pip:
    name: celery[{{ item }}]
    version: "{{ celery_version }}"
  with_items: "{{ celery_extra_packages }}"
  when: airflow_executor == "CeleryExecutor" and celery_extra_packages

- name: Set AIRFLOW_HOME environment variable in /etc/environment
  lineinfile:
    path: /etc/environment
    line: 'AIRFLOW_HOME={{ airflow_home }}'

- name: Install Airflow
  pip:
    name: apache-airflow
    version: "{{ airflow_version }}"
  register: airflow_install

- name: Install Airflow extra packages
  pip:
    name: apache-airflow[{{ item }}]
    version: "{{ airflow_version }}"
  with_items: "{{ airflow_extra_packages }}"
