---

- name: AIRFLOW BACKEND | Create Airflow database on Postgres DB
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ postgres_db_name }}"

- name: AIRFLOW BACKEND | Create Airflow role on Postgres DB
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{ postgres_db_name }}"
    name: "{{ postgres_role_name }}"
    password: "md5{{ (postgres_role_password + postgres_role_name)|hash('md5') }}"
    encrypted: yes
    priv: CONNECT

- name: AIRFLOW BACKEND | Set default Airflow privileges
  become: yes
  become_user: postgres
  postgresql_privs:
    database: "{{ postgres_db_name }}"
    state: present
    privs: ALL
    type: database
    roles: "{{ postgres_role_name }}"

- name: AIRFLOW BACKEND | Configure password remote authentication from Airflow hosts
  lineinfile:
    dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    insertafter: "# IPv4 local connections:"
    line: 'host {{ postgres_db_name }} {{ postgres_role_name }} {{ item }}/32 md5'
  with_inventory_hostnames: airflow

- name: AIRFLOW BACKEND | Ensure postgresql is restarted
  systemd:
    name: postgresql
    state: restarted
