---

- name: AIRFLOW USERS | Install prerequisites packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - { name: "sqlalchemy", version: "{{ airflow_sqlalchemy_version }}" }

- name: AIRFLOW USERS | Deploy Airflow user script management
  template:
    src: "opt/airflow/add_credentials.py.j2"
    dest: "{{ airflow_temp }}/add_credentials.py"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0644
  register: update_airflow_user

- name: AIRFLOW USERS | Create Airflow user
  command: "python {{ airflow_temp }}/add_credentials.py"
  when: update_airflow_user.changed
