---

- name: Check if user script exists
  stat:
    path: /opt/airflow/add_credentials.py
  register: airflow_user
  changed_when: False

- block:

  - name: Install prerequisites packages
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    with_items:
      - { name: "sqlalchemy", version: 1.1.17 }

  - name: Deploy Airflow user script management
    template:
      src: "opt/airflow/add_credentials.py.j2"
      dest: "{{ airflow_temp }}/add_credentials.py"
      owner: "{{ airflow_user }}"
      group: "{{ airflow_group }}"
      mode: 0644

  - name: Create Airflow user
    command: "python {{ airflow_temp }}/add_credentials.py"

  - name: Delete Airflow user script management
    file:
      path: "{{ airflow_temp }}/add_credentials.py"
      state: absent

  when: not airflow_user.stat.exists
